### ISSUE TITLE
Blitzwolf BW-SHP2 can't be found

### ISSUE THREAD

**Issue by voodoobg** [ct-Open-Source/tuya-convert#160]
I have followed the install procedure and tried it on 2 raspberry pi's 3B and 1B with wifi adapter.
The outcome is the same, tuya-convert cannot pick up the plugs ( I have 3 )
I tried one with the tuya app and everything works ok.
Here are the logs on the raspi 1b with the wifi adapter, I can provide the other logs with raspi3B :
https://pastebin.com/mX3mAxWq

**Comment by kueblc** [comment]
Can you record your network activity with `tcpdump` or Wireshark and share the capture files? What firmware version are the plugs?

**Comment by voodoobg** [comment]
Version is 1.0.5, here is the tcp dump:
https://pastebin.com/F4ide0VD

**Comment by kueblc** [comment]
Is your device `10.42.42.23`? Looks like it's trying to talk to Home Assistant

**Comment by voodoobg** [comment]
Indeed this is strange in the logs i saw it too. My network is on very different ip range than this ip. I have pihole as dns resolver and my router is on ddwrt with  DNSMasq as you can see in the logs. The device is tablet with HADashboard installed, maybe this is requesting Home Assistant. Is this relevant to the convert script? What device should I use? I've tried also my phone, the result was the same.

**Comment by voodoobg** [comment]
I've read the thread for the 1.0.5 firmware... So i'll try with the Kali Linux way, since one guy reported working. My switches came with the 1.0.5 version, maybe that's why tuya-convert didn't work. I'll post the dump of the stock firmware when i get it, if it works from the Kali.

**Comment by kueblc** [comment]
I'm not sure I can identify your smart device in the `tcpdump`. Do you see your plug's mac or IP in the log?

It shouldn't make too much of a difference with Kali linux. If the issue is that the firmware is too new, it'll make requests via HTTPS instead of HTTP, and then we're out of luck for the time being, no matter what OS.

It's inconclusive as to whether your SHP2 firmware has the HTTPS update. Firmware versioning is per device, so Blitzwolf firmware 1.0.5 isn't necessarily the same as Teckin 1.0.5.

If you do discover that the device is demanding HTTPS, the only method for flashing we have available right now is to flash it "the old fashion way" by physically opening the device and flashing it over the serial port. If you decide to do that, you can make a backup first, and that would be tremendously useful in reverse engineering efforts to update the `tuya-convert` process for the new firmware updates.

**Comment by pcmester** [comment]
My BW-SHP2 arrived yesterday, and I think they applied the patch to the new ones, because it connects, but the script does not continue

**Comment by JBS5** [comment]
Tried it with a BlitzWolf SHP2 which I received a few days ago, but no luck finding it after the './start_flash.sh' command. Any way to fix this?

**Comment by jokerigno** [comment]
any update?

**Comment by eterpstra** [comment]
How can I check the firmware of my SPH111 withhout connecting it to the internet?

**Comment by sebastianklein96** [comment]
@eterpstra If you're not soldering to it and dumping the firmware via serial, I don't think you can. Tuya-connect not recognizing the device is a pretty good indicator for new firmware though, if you're sure you set up everything correctly.

**Comment by eterpstra** [comment]
@sebastianklein96 Yeah i am pretty sure of my setup.. have flashd 8 socks without any problems a few weeks ago... The other problem is that i bought a 4 pack of these SP111 Go-sund plugs.. 1 was flashed succesfully,bot the other 3 are not working.. So i cant send them back to Amazon I guess :P

**Comment by probonopd** [comment]
To everyone having issues: Have you connected the light bulb to the app/the internet before flashing?

**Comment by eterpstra** [comment]
Not a light bulb but my sp111 power plug was straight from the box without connecting it to the internet

**Comment by jokerigno** [comment]
> To everyone having issues: Have you connected the light bulb to the app/the internet before flashing?

Nope.

**Comment by Ixtalo** [comment]
New v2.4 20181101 devices (bought 05/2019) have a new firmware with version 1.06; old working versions were 1.05.
New devices with new firmware v1.06 use HTTPS (e.g., https://a3.tuyaus.com/gw.json, found in firmware) and try to connect to port 443 (instead of 80).
Firmware hacking scripts do not work with that, i.e., the `start_flash.sh` script hangs in endless loop because no 10.42.42.42 device is to be found.

See also:
#195 
#197 
#199 
...

**Comment by Niek** [comment]
Also: https://github.com/ct-Open-Source/tuya-convert/issues/166

**Comment by kueblc** [comment]
Happy to share #279 support for newer firmware
