### ISSUE TITLE
Updating Sonoff-Tasmota to 6.6.0

### ISSUE THREAD

**Issue by rlfnb** [ct-Open-Source/tuya-convert#250]
Sonoff Tasmota released already on 6th of June a new version (6.6.0), would be great to update the version here as well?

**Comment by meingraham** [comment]
6.6.0 had some issues. If you are going to replace it in the package, go ahead and grab 6.6.0.4 at http://thehackbox.org/tasmota/020300/sonoff.bin. And yes, sonoff.bin rather than sonoff-basic.bin. We are recommending to those that do get their device to flash with Tuya-Convert to immediately upgrade to sonoff.bin... so it would just be best to have the package do that directly.

**Comment by kueblc** [comment]
Feel free to make a PR otherwise I think the current situation is fine. It is intended that you flash another bin after the conversion is complete.
